package com.epam.zhuckovich.command;

/**
 * Enum which contains different action for different realeasation of Command functional interface
 */

public enum CommandType {
    ADD_AUTHOR, ADD_BOOK, ADD_LIBRARIAN, ADD_BOOK_MENU, DELETE_ACCOUNT, DELETE_BOOK,
    DELETE_BOOK_MENU, DELETE_LIBRARIAN_MENU, DELETE_MEMBER_MENU, DELETE_USER, EDIT_ACCOUNT,
    EDIT_BOOK, EDIT_BOOKS_MENU, LOGIN, LOGOUT, ORDER_BOOK, READING_ROOM_ISSUE, READING_ROOM_MENU,
    REGISTER, RETURN_BOOK, SEARCH, SUBSCRIPTION_ISSUE, SUBSCRIPTION_MENU, VIEW_AUTHORS,
    VIEW_ORDERED_BOOKS
}
